---
title: "Using Chlorophyll *a*  as a surrogate for exceeding Microcystin Health Advisory Concentrations"
subtitle: "Cyanobacteria - Monitoring and Treating Drinking Water: A Workshop for Water Suppliers"
author: "Jeff Hollister and Betty Kreakie"
date: |
  | 2017-12-014
  | Worcester, MA
output:
  xaringan::moon_reader:
    css: ["default", "custom.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: true
---
class: center, middle, inverse

# The Problem: What is a bloom?

---

- So of course, I asked Twitter

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Some help, twitter. What is definition of an algal bloom? rate of increase? exceed some min conc? <a href="https://twitter.com/GLEONetwork?ref_src=twsrc%5Etfw">@GLEONetwork</a>  <a href="https://twitter.com/KathyCottingham?ref_src=twsrc%5Etfw">@KathyCottingham</a> <a href="https://twitter.com/not_Klaatu?ref_src=twsrc%5Etfw">@not_Klaatu</a></p>&mdash; Jeff Hollister (@jhollist) <a href="https://twitter.com/jhollist/status/611192646015520768?ref_src=twsrc%5Etfw">June 17, 2015</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

---

- Got some of this variety

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/WiscLimnology?ref_src=twsrc%5Etfw">@WiscLimnology</a> <a href="https://twitter.com/CareyLab?ref_src=twsrc%5Etfw">@CareyLab</a> <a href="https://twitter.com/jhollist?ref_src=twsrc%5Etfw">@jhollist</a> <a href="https://twitter.com/GLEONetwork?ref_src=twsrc%5Etfw">@GLEONetwork</a>  Snot green water?</p>&mdash; Jim Garvey (@fishysiu) <a href="https://twitter.com/fishysiu/status/611197989047148544?ref_src=twsrc%5Etfw">June 17, 2015</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">.<a href="https://twitter.com/jhollist?ref_src=twsrc%5Etfw">@jhollist</a> <a href="https://twitter.com/fishysiu?ref_src=twsrc%5Etfw">@fishysiu</a> <a href="https://twitter.com/CareyLab?ref_src=twsrc%5Etfw">@CareyLab</a> <a href="https://twitter.com/GLEONetwork?ref_src=twsrc%5Etfw">@GLEONetwork</a> I know it when I see it?</p>&mdash; Center for Limnology (@WiscLimnology) <a href="https://twitter.com/WiscLimnology/status/611244709076430848?ref_src=twsrc%5Etfw">June 17, 2015</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

---

- Got some of the more quantitative

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">1/2 <a href="https://twitter.com/jhollist?ref_src=twsrc%5Etfw">@jhollist</a> <a href="https://twitter.com/fishysiu?ref_src=twsrc%5Etfw">@fishysiu</a> <a href="https://twitter.com/WiscLimnology?ref_src=twsrc%5Etfw">@WiscLimnology</a> <a href="https://twitter.com/CareyLab?ref_src=twsrc%5Etfw">@CareyLab</a> &#39;Bloom&#39; is a loose term 4 an abundance of algae; con varies in marine &amp; freshwater environ</p>&mdash; GLEON (@GLEONetwork) <a href="https://twitter.com/GLEONetwork/status/611247529104154624?ref_src=twsrc%5Etfw">June 17, 2015</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">2/2 <a href="https://twitter.com/jhollist?ref_src=twsrc%5Etfw">@jhollist</a> <a href="https://twitter.com/fishysiu?ref_src=twsrc%5Etfw">@fishysiu</a> <a href="https://twitter.com/WiscLimnology?ref_src=twsrc%5Etfw">@WiscLimnology</a> <a href="https://twitter.com/CareyLab?ref_src=twsrc%5Etfw">@CareyLab</a> via <a href="https://twitter.com/caweirich?ref_src=twsrc%5Etfw">@caweirich</a> <a href="https://twitter.com/TrexLab?ref_src=twsrc%5Etfw">@TrexLab</a> definition: 1.5X baseline phycocyanin above <a href="http://t.co/u1eULIpFT5">http://t.co/u1eULIpFT5</a></p>&mdash; GLEON (@GLEONetwork) <a href="https://twitter.com/GLEONetwork/status/611251043364683776?ref_src=twsrc%5Etfw">June 17, 2015</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

---

- and then the one closest to reality

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/jhollist?ref_src=twsrc%5Etfw">@jhollist</a> Alternative view: when the public notices and starts phoning?</p>&mdash; Kathy Cottingham (@KathyCottingham) <a href="https://twitter.com/KathyCottingham/status/611641747886710785?ref_src=twsrc%5Etfw">June 18, 2015</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


---
# Slide with left and right columns

.left-column[
- Ecologists 
- Computational focus
  - Enough to be dangerous
- 3 FTE
  - Myself
  - Betty Kreakie
  - Bryan Milstead
- 2 Post-docs
  - Farnaz Nojavan
  - Stephen Shivers
]

.right-column[
```{r}
icon::fa("rocket", size = 4)
```
]

---

# No column slide

- Apply computational approaches to understand water quality impacts in lakes
  - Modelling (Not this talk!, but see Farnaz's talk)
- Open Science

---
# Thanks!
.center[
## Jeff Hollister
US EPA </br>
Atlantic Ecology Division </br>
Narragansett, RI </br>

`r icon::fa("envelope", size = 1.5)`: [hollister.jeff@epa.gov](mailto:hollister.jeff@epa.gov) </br>
`r icon::fa("twitter", size = 1.5)`: [jhollist](https://twitter.com/jhollist) </br>
`r icon::fa("github", size = 1.5)`: [jhollist](https://github.com/jhollist) </br>

Slides created via the R package [**xaringan**](https://github.com/yihui/xaringan).
]

